<?php 
require_once 'includes/CMS.php';
$meta = CMS::getPageMeta();
?>
<!DOCTYPE html>
<html lang="cs">
<head>
    <?php include 'includes/head.php'; ?>
    <style>* { box-sizing: border-box; } body {margin: 0;}*{box-sizing:border-box;}body{margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;}.event-type-card{background-color:white;background-position-x:0%;background-position-y:0%;background-repeat:repeat;background-attachment:scroll;background-image:none;background-size:auto;background-origin:padding-box;background-clip:border-box;border-top-left-radius:12px;border-top-right-radius:12px;border-bottom-right-radius:12px;border-bottom-left-radius:12px;overflow-x:hidden;overflow-y:hidden;box-shadow:var(--shadow);margin-bottom:4rem;display:grid;grid-template-columns:1fr 1fr;align-items:center;}.event-type-card:nth-child(2n){grid-template-columns:1fr 1fr;}.event-type-card:nth-child(2n) .event-type-img{order:2;}.event-type-card:nth-child(2n) .event-type-content{order:1;}.event-type-img{width:100%;height:100%;min-height:400px;object-fit:cover;}.event-type-content{padding-top:4rem;padding-right:4rem;padding-bottom:4rem;padding-left:4rem;}.amenities-grid{display:grid;grid-template-columns:repeat(auto-fit, minmax(200px, 1fr));row-gap:2rem;column-gap:2rem;margin-top:3rem;}.amenity-item{text-align:center;padding-top:2rem;padding-right:2rem;padding-bottom:2rem;padding-left:2rem;border-top-left-radius:8px;border-top-right-radius:8px;border-bottom-right-radius:8px;border-bottom-left-radius:8px;}.amenity-icon{color:var(--primary);margin-bottom:1rem;font-size:1.5rem;}#iaaz{background-image:url("assets/img/wedding.png");}#i7u2{height:70vh;min-height:500px;}#ixxgm{max-width:800px;margin-inline-start:auto;margin-inline-end:auto;}#i35pu{font-size:2rem;}#icez4{margin-bottom:1.5rem;}#itq9h{margin-top:1rem;}#im1l3{font-size:2rem;}#ioxbp{margin-bottom:1.5rem;}#ix0fd{margin-top:1rem;}#i5dj7{font-size:2rem;}#i16uk{margin-bottom:1.5rem;}#i3ghs{padding-bottom:0px;}#ioxtw{margin-bottom:4rem;}#ixqwih{max-width:600px;margin-inline-start:auto;margin-inline-end:auto;margin-bottom:2rem;}@media (max-width: 992px){.event-type-card{grid-template-columns:1fr !important;}.event-type-img{height:300px;min-height:auto;}.event-type-content{padding-top:2rem;padding-right:2rem;padding-bottom:2rem;padding-left:2rem;}.event-type-card:nth-child(2n) .event-type-img{order:1;}.event-type-card:nth-child(2n) .event-type-content{order:2;}}</style>
</head>
<body>
    <?php include 'includes/header.php'; ?>
    
    <main>
        <body><!--?php include 'includes/header.php'; ?--><main><!--?php include 'includes/header.php'; ?--><!-- Hero Section --><title>Svatby a akce na statku | Penzion Statek Straňovice</title><meta name="description" content="Uspořádejte svou pohádkovou svatbu, firemní teambuilding nebo rodinnou oslavu v autentickém prostředí jihočeského statku v Malenicích."/><section id="i7u2" class="hero"><div id="iaaz" class="hero-bg"></div><div class="hero-overlay"></div><div class="container hero-content"><h2 class="hero-subtitle fadeIn">Nezapomenutelné okamžiky</h2><h1 class="hero-title fadeInDelay">Svatby &amp; Akce </h1></div></section><!-- Intro --><section class="section-padding"><div id="ixxgm" class="container text-center"><span class="section-tag">Váš den u nás</span><h2 class="section-title">Místo, kde příběhy začínají</h2><p class="section-description">
                Hledáte netradiční a autentické místo pro Vaši životní událost nebo firemní setkání? Náš statek nabízí unikátní kombinaci jihočeské venkovské architektury, klidné přírody a moderního zázemí. 
            </p></div></section><!-- Event Types --><section id="i3ghs" class="section-padding bg-light"><div class="container"><!-- Weddings --><div class="event-type-card reveal"><img src="assets/img/wedding.png" alt="Svatba na statku" class="event-type-img"/><div class="event-type-content"><span id="i35pu" class="section-tag">Pohádková</span><h2 id="icez4">Svatba na statku</h2><p>Užijte si svůj svatební den bez stresu a v naprostém soukromí. Nabízíme možnost obřadu přímo v našem areálu, hostinu ve stylově upravených prostorách a ubytování pro novomanžele i hosty.</p><p id="itq9h">Kapacita pro hostinu: až 60 osob.</p></div></div><!-- Corporate --><div class="event-type-card reveal-up"><img src="assets/img/event.png" alt="Firemní akce" class="event-type-img"/><div class="event-type-content"><span id="im1l3" class="section-tag">Profesionální</span><h2 id="ioxbp">Firemní akce &amp; Teambuilding</h2><p>Vyměňte sterilní kanceláře za inspirativní prostředí venkova. Náš statek je ideální pro menší konference, školení nebo neformální teambuildingy s možností doprovodných aktivit na farmě.</p><p id="ix0fd">K dispozici: Wi-Fi, projekce, catering na míru.</p></div></div><!-- Private --><div class="event-type-card reveal"><img src="assets/img/hero.jpg" alt="Soukromé oslavy" class="event-type-img"/><div class="event-type-content"><span id="i5dj7" class="section-tag">Osobní</span><h2 id="i16uk">Soukromé oslavy &amp; Výročí</h2><p>Narozeniny, rodinné srazy nebo setkání přátel. U nás najdete klid a prostor pro nerušenou zábavu. Zajistíme pro Vás rauty z našich domácích surovin i grilování na dvoře.</p></div></div></div></section><!-- Amenities Grid --><section class="section-padding"><div class="container"><div id="ioxtw" class="text-center"><span class="section-tag">Co u nás najdete</span><h2 class="section-title">Kompletní zázemí</h2></div><div class="amenities-grid"><div class="amenity-item reveal"><div class="amenity-icon"><i data-lucide="utensils"></i></div><h4>Catering</h4><p>Domácí kuchyně z vlastních surovin</p></div><div class="amenity-item reveal-up"><div class="amenity-icon"><i data-lucide="home"></i></div><h4>Ubytování</h4><p>Pohodlné apartmány pro Vaše hosty</p></div><div class="amenity-item reveal"><div class="amenity-icon"><i data-lucide="parking-circle"></i></div><h4>Parkování</h4><p>Bezplatné parkování přímo v areálu</p></div><div class="amenity-item reveal-up"><div class="amenity-icon"><i data-lucide="wifi"></i></div><h4>Konektivita</h4><p>Wi-Fi v celém areálu zdarma</p></div></div></div></section><!-- CTA --><section class="section-padding bg-light text-center"><div class="container"><h2 class="section-title">Plánujete akci?</h2><p id="ixqwih">
                Rádi Vám pomůžeme s organizací a připravíme nabídku přesně podle Vašich představ.
            </p><a href="index.php#contact" class="btn btn-primary btn-lg">Poptat termín</a></div></section><!--?php include 'includes/footer.php'; ?--></main><!--?php include 'includes/footer.php'; ?--></body>
    </main>

    <?php include 'includes/footer.php'; ?>
    <script>if (typeof lucide !== 'undefined') lucide.createIcons();</script>
</body>
</html>