<?php
require_once __DIR__ . '/../admin/includes/CMS.php';
CMS::getHeader();
?>
<style>* { box-sizing: border-box; } body {margin: 0;}.animal-showcase{display:grid;grid-template-columns:repeat(auto-fit, minmax(280px, 1fr));row-gap:2rem;column-gap:2rem;margin-top:3rem;}.animal-card{background-color:white;background-position-x:0%;background-position-y:0%;background-repeat:repeat;background-attachment:scroll;background-image:none;background-size:auto;background-origin:padding-box;background-clip:border-box;border-top-left-radius:12px;border-top-right-radius:12px;border-bottom-right-radius:12px;border-bottom-left-radius:12px;overflow-x:hidden;overflow-y:hidden;box-shadow:var(--shadow);display:flex;flex-direction:column;height:100%;}.animal-card:hover{transform:translateY(-5px);}.animal-img-wrapper{height:220px;width:100%;overflow-x:hidden;overflow-y:hidden;position:relative;}.animal-img-wrapper img{width:100%;height:100%;object-fit:cover;transition-property:transform;transition-duration:0.6s;transition-timing-function:ease;transition-delay:0s;transition-behavior:normal;}.animal-card:hover .animal-img-wrapper img{transform:scale(1.08);}.animal-body{padding-top:1.5rem;padding-right:1.5rem;padding-bottom:1.5rem;padding-left:1.5rem;display:flex;flex-direction:column;flex-grow:1;background-color:white;background-position-x:0%;background-position-y:0%;background-repeat:repeat;background-attachment:scroll;background-image:none;background-size:auto;background-origin:padding-box;background-clip:border-box;}.animal-name{font-family:"Libre Baskerville", serif;font-size:1.25rem;color:var(--primary);margin-bottom:0.8rem;font-weight:700;}.animal-desc{color:var(--text-muted);font-size:0.9rem;line-height:1.5;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;}.farm-life{display:grid;grid-template-columns:1.2fr 0.8fr;row-gap:5rem;column-gap:5rem;align-items:center;}#itxr{background-image:url(/assets/img/chov_hero.png);}#ifwb{height:60vh;min-height:450px;}#iec15{border-radius:20px;box-shadow:var(--shadow-lg);width:100%;}#iiq8g{animation-delay:0.1s;}#i8cmq{animation-delay:0.2s;}#ildr8{animation-delay:0.3s;}#i9ljp{animation-delay:0.4s;}#igkbr{animation-delay:0.5s;}#ib8pd{max-width:600px;margin-inline:auto;margin-bottom:2rem;}#iomdr{display:flex;gap:1rem;justify-content:center;}@media (max-width: 992px){.farm-life{grid-template-columns:1fr;row-gap:3rem;column-gap:3rem;}}</style>
<body class="bg-slate-950 text-slate-100 min-h-screen"><section class="hero" id="ifwb"><div class="hero-bg" id="itxr"></div><div class="hero-overlay"></div><div class="container hero-content"><h2 class="hero-subtitle fadeIn">Život v souladu s přírodou</h2><h1 class="hero-title fadeInDelay">Chov zvířat</h1></div></section><!-- Intro --><section class="section-padding"><div class="container"><div class="farm-life"><div class="reveal"><span class="section-tag">Naše srdce</span><h2 class="section-title">Zvířata jsou naše rodina</h2><p class="section-description">
                        Hospodaření na statku Straňovice není jen práce, je to životní styl. Naše zvířata mají dostatek volnosti na pastvinách a dostávají tu nejlepší péči. Věříme, že spokojené zvíře je základem kvalitních produktů a radosti, kterou naše farma přináší návštěvníkům.
                    </p><p>
                        Věnujeme se chovu hospodářských zvířat – krav, koní, ovcí, koz, drůbeže, včel a drobného zvířectva. Naši hosté mají možnost se se zvířaty seznámit zblízka, pod dohledem si vyzkoušet péči o ně nebo se jen tak kochat pohledem na pasoucí se stáda.
                    </p></div><div class="reveal-up"><img src="/assets/img/horse_stable.png" alt="Naše stáj" id="iec15"/></div></div><div class="animal-showcase"><!-- Animal 1 --><div class="animal-card reveal"><div class="animal-img-wrapper"><img src="/assets/img/horse_hero.png" alt="Koně"/></div><div class="animal-body"><h3 class="animal-name">Koně</h3><p class="animal-desc">Nabízíme možnost ustájení i pohodový relax s koňmi v čisté pošumavské přírodě.</p></div></div><!-- Animal 2 --><div class="animal-card reveal-up" id="iiq8g"><div class="animal-img-wrapper"><img src="/assets/img/sheep_goats.png" alt="Ovce a kozy"/></div><div class="animal-body"><h3 class="animal-name">Ovce a kozy</h3><p class="animal-desc">Přirození údržbáři našich luk a pastvin, kteří dělají radost všem návštěvníkům.</p></div></div><!-- Animal 3 --><div class="animal-card reveal" id="i8cmq"><div class="animal-img-wrapper"><img src="/assets/img/poultry.png" alt="Slepice a křepelky"/></div><div class="animal-body"><h3 class="animal-name">Slepice a křepelky</h3><p class="animal-desc">Slepice, křepelky, kachny a husy, které se volně pohybují po celém dvoře.</p></div></div><!-- Animal 4 --><div class="animal-card reveal-up" id="ildr8"><div class="animal-img-wrapper"><img src="/assets/img/cows_pasture_1786308319266.png" alt="Chov krav" id="ihx3n"/></div><div class="animal-body"><h3 class="animal-name">Chov krav</h3><p class="animal-desc">Tradiční chov skotu pasoucího se na okolních šťavnatých lukách.</p></div></div><!-- Animal 5 --><div class="animal-card reveal" id="i9ljp"><div class="animal-img-wrapper"><img src="/assets/img/bees.png" alt="Včely a včelařství"/></div><div class="animal-body"><h3 class="animal-name">Včely a včelařství</h3><p class="animal-desc">Naše včelstva pečují o opylování okolní přírody a doplňují život na statku o poctivý domácí med.</p></div></div><!-- Animal 6 --><div class="animal-card reveal-up" id="igkbr"><div class="animal-img-wrapper"><img src="/assets/img/small_animals.png" alt="Drobné zvířectvo a mazlíčkové"/></div><div class="animal-body"><h3 class="animal-name">Drobné zvířectvo a mazlíčkové</h3><p class="animal-desc">Kočky, králíci a morčata pro radost dětí i dospělých návštěvníků statku.</p></div></div></div></div></section><!-- Products CTA --><section class="section-padding bg-light text-center"><div class="container"><h2 class="section-title">Chcete ochutnat výsledky naší práce?</h2><p id="ib8pd">
                Mnoho produktů z našeho chovu si můžete zakoupit přímo u nás "ze dvora" nebo ochutnat v rámci našich bohatých snídaní.
            </p><div id="iomdr"><a href="prodej.php" class="btn btn-primary">Prodej ze dvora</a><a href="galerie.php" class="btn btn-outline-primary">Prohlédnout fotogalerii</a></div></div></section><!--?php CMS::getFooter(); ?--></body>
<?php
CMS::getFooter();
?>